/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneysIndexRouteImport } from './routes/journeys.index'
import { Route as JourneysSlugRouteImport } from './routes/journeys.$slug'

const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysIndexRoute = JourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysSlugRoute = JourneysSlugRouteImport.update({
  id: '/journeys/$slug',
  path: '/journeys/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guides': typeof GuidesRoute
  '/journal': typeof JournalRoute
  '/journeys/$slug': typeof JourneysSlugRoute
  '/journeys/': typeof JourneysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guides': typeof GuidesRoute
  '/journal': typeof JournalRoute
  '/journeys/$slug': typeof JourneysSlugRoute
  '/journeys': typeof JourneysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guides': typeof GuidesRoute
  '/journal': typeof JournalRoute
  '/journeys/$slug': typeof JourneysSlugRoute
  '/journeys/': typeof JourneysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guides' | '/journal' | '/journeys/$slug' | '/journeys/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guides' | '/journal' | '/journeys/$slug' | '/journeys'
  id:
    | '__root__'
    | '/'
    | '/guides'
    | '/journal'
    | '/journeys/$slug'
    | '/journeys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuidesRoute: typeof GuidesRoute
  JournalRoute: typeof JournalRoute
  JourneysSlugRoute: typeof JourneysSlugRoute
  JourneysIndexRoute: typeof JourneysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/': {
      id: '/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof JourneysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/$slug': {
      id: '/journeys/$slug'
      path: '/journeys/$slug'
      fullPath: '/journeys/$slug'
      preLoaderRoute: typeof JourneysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidesRoute: GuidesRoute,
  JournalRoute: JournalRoute,
  JourneysSlugRoute: JourneysSlugRoute,
  JourneysIndexRoute: JourneysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
